// Code generated by protoc-gen-go. DO NOT EDIT.
// source: a_bit_of_everything.proto

package examplepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 枚举 enum
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_OK          Status = 1
	Status_STATUS_FAIL        Status = 2
	Status_STATUS_UNKNOWN     Status = -1
)

var Status_name = map[int32]string{
	0:  "STATUS_UNSPECIFIED",
	1:  "STATUS_OK",
	2:  "STATUS_FAIL",
	-1: "STATUS_UNKNOWN",
}

var Status_value = map[string]int32{
	"STATUS_UNSPECIFIED": 0,
	"STATUS_OK":          1,
	"STATUS_FAIL":        2,
	"STATUS_UNKNOWN":     -1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{0}
}

// 保留枚举
type ReservedEnum int32

const (
	// FOO = 0; 编译报错
	ReservedEnum_F ReservedEnum = 0
)

var ReservedEnum_name = map[int32]string{
	0: "F",
}

var ReservedEnum_value = map[string]int32{
	"F": 0,
}

func (x ReservedEnum) String() string {
	return proto.EnumName(ReservedEnum_name, int32(x))
}

func (ReservedEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{1}
}

type SearchResponse_Status int32

const (
	SearchResponse_UNSPECIFIED SearchResponse_Status = 0
	SearchResponse_OK          SearchResponse_Status = 1
	SearchResponse_FAIL        SearchResponse_Status = 2
)

var SearchResponse_Status_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "OK",
	2: "FAIL",
}

var SearchResponse_Status_value = map[string]int32{
	"UNSPECIFIED": 0,
	"OK":          1,
	"FAIL":        2,
}

func (x SearchResponse_Status) String() string {
	return proto.EnumName(SearchResponse_Status_name, int32(x))
}

func (SearchResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{2, 0}
}

// 普通的message
type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

// 保留字段
type ReservedMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservedMessage) Reset()         { *m = ReservedMessage{} }
func (m *ReservedMessage) String() string { return proto.CompactTextString(m) }
func (*ReservedMessage) ProtoMessage()    {}
func (*ReservedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{1}
}

func (m *ReservedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservedMessage.Unmarshal(m, b)
}
func (m *ReservedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservedMessage.Marshal(b, m, deterministic)
}
func (m *ReservedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservedMessage.Merge(m, src)
}
func (m *ReservedMessage) XXX_Size() int {
	return xxx_messageInfo_ReservedMessage.Size(m)
}
func (m *ReservedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReservedMessage proto.InternalMessageInfo

// nested 嵌套message
type SearchResponse struct {
	Result               *SearchResponse_Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status               SearchResponse_Status  `protobuf:"varint,2,opt,name=status,proto3,enum=example.everything.SearchResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{2}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetResult() *SearchResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *SearchResponse) GetStatus() SearchResponse_Status {
	if m != nil {
		return m.Status
	}
	return SearchResponse_UNSPECIFIED
}

type SearchResponse_Result struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse_Result) Reset()         { *m = SearchResponse_Result{} }
func (m *SearchResponse_Result) String() string { return proto.CompactTextString(m) }
func (*SearchResponse_Result) ProtoMessage()    {}
func (*SearchResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{2, 0}
}

func (m *SearchResponse_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse_Result.Unmarshal(m, b)
}
func (m *SearchResponse_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse_Result.Marshal(b, m, deterministic)
}
func (m *SearchResponse_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse_Result.Merge(m, src)
}
func (m *SearchResponse_Result) XXX_Size() int {
	return xxx_messageInfo_SearchResponse_Result.Size(m)
}
func (m *SearchResponse_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse_Result proto.InternalMessageInfo

func (m *SearchResponse_Result) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SearchResponse_Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type OtherResponse struct {
	Result               *SearchResponse_Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status               SearchResponse_Status  `protobuf:"varint,2,opt,name=status,proto3,enum=example.everything.SearchResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OtherResponse) Reset()         { *m = OtherResponse{} }
func (m *OtherResponse) String() string { return proto.CompactTextString(m) }
func (*OtherResponse) ProtoMessage()    {}
func (*OtherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{3}
}

func (m *OtherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OtherResponse.Unmarshal(m, b)
}
func (m *OtherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OtherResponse.Marshal(b, m, deterministic)
}
func (m *OtherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OtherResponse.Merge(m, src)
}
func (m *OtherResponse) XXX_Size() int {
	return xxx_messageInfo_OtherResponse.Size(m)
}
func (m *OtherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OtherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OtherResponse proto.InternalMessageInfo

func (m *OtherResponse) GetResult() *SearchResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *OtherResponse) GetStatus() SearchResponse_Status {
	if m != nil {
		return m.Status
	}
	return SearchResponse_UNSPECIFIED
}

// repeated
type RepeatedMessage struct {
	Requests             []*SearchRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Status               []Status         `protobuf:"varint,2,rep,packed,name=status,proto3,enum=example.everything.Status" json:"status,omitempty"`
	Number               []int32          `protobuf:"varint,3,rep,packed,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RepeatedMessage) Reset()         { *m = RepeatedMessage{} }
func (m *RepeatedMessage) String() string { return proto.CompactTextString(m) }
func (*RepeatedMessage) ProtoMessage()    {}
func (*RepeatedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{4}
}

func (m *RepeatedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedMessage.Unmarshal(m, b)
}
func (m *RepeatedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedMessage.Marshal(b, m, deterministic)
}
func (m *RepeatedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedMessage.Merge(m, src)
}
func (m *RepeatedMessage) XXX_Size() int {
	return xxx_messageInfo_RepeatedMessage.Size(m)
}
func (m *RepeatedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedMessage proto.InternalMessageInfo

func (m *RepeatedMessage) GetRequests() []*SearchRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *RepeatedMessage) GetStatus() []Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RepeatedMessage) GetNumber() []int32 {
	if m != nil {
		return m.Number
	}
	return nil
}

// any
type AnyMessage struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Details              *any.Any `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnyMessage) Reset()         { *m = AnyMessage{} }
func (m *AnyMessage) String() string { return proto.CompactTextString(m) }
func (*AnyMessage) ProtoMessage()    {}
func (*AnyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{5}
}

func (m *AnyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnyMessage.Unmarshal(m, b)
}
func (m *AnyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnyMessage.Marshal(b, m, deterministic)
}
func (m *AnyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnyMessage.Merge(m, src)
}
func (m *AnyMessage) XXX_Size() int {
	return xxx_messageInfo_AnyMessage.Size(m)
}
func (m *AnyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AnyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AnyMessage proto.InternalMessageInfo

func (m *AnyMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AnyMessage) GetDetails() *any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

// one of
type OneOfMessage struct {
	// Types that are valid to be assigned to TestOneof:
	//	*OneOfMessage_M1
	//	*OneOfMessage_M2
	TestOneof            isOneOfMessage_TestOneof `protobuf_oneof:"test_oneof"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OneOfMessage) Reset()         { *m = OneOfMessage{} }
func (m *OneOfMessage) String() string { return proto.CompactTextString(m) }
func (*OneOfMessage) ProtoMessage()    {}
func (*OneOfMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{6}
}

func (m *OneOfMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneOfMessage.Unmarshal(m, b)
}
func (m *OneOfMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneOfMessage.Marshal(b, m, deterministic)
}
func (m *OneOfMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneOfMessage.Merge(m, src)
}
func (m *OneOfMessage) XXX_Size() int {
	return xxx_messageInfo_OneOfMessage.Size(m)
}
func (m *OneOfMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OneOfMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OneOfMessage proto.InternalMessageInfo

type isOneOfMessage_TestOneof interface {
	isOneOfMessage_TestOneof()
}

type OneOfMessage_M1 struct {
	M1 string `protobuf:"bytes,1,opt,name=m1,proto3,oneof"`
}

type OneOfMessage_M2 struct {
	M2 int32 `protobuf:"varint,2,opt,name=m2,proto3,oneof"`
}

func (*OneOfMessage_M1) isOneOfMessage_TestOneof() {}

func (*OneOfMessage_M2) isOneOfMessage_TestOneof() {}

func (m *OneOfMessage) GetTestOneof() isOneOfMessage_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (m *OneOfMessage) GetM1() string {
	if x, ok := m.GetTestOneof().(*OneOfMessage_M1); ok {
		return x.M1
	}
	return ""
}

func (m *OneOfMessage) GetM2() int32 {
	if x, ok := m.GetTestOneof().(*OneOfMessage_M2); ok {
		return x.M2
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OneOfMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OneOfMessage_M1)(nil),
		(*OneOfMessage_M2)(nil),
	}
}

// map
type MapMessage struct {
	Message              map[string]string         `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Request              map[string]*SearchRequest `protobuf:"bytes,2,rep,name=request,proto3" json:"request,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MapMessage) Reset()         { *m = MapMessage{} }
func (m *MapMessage) String() string { return proto.CompactTextString(m) }
func (*MapMessage) ProtoMessage()    {}
func (*MapMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{7}
}

func (m *MapMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapMessage.Unmarshal(m, b)
}
func (m *MapMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapMessage.Marshal(b, m, deterministic)
}
func (m *MapMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapMessage.Merge(m, src)
}
func (m *MapMessage) XXX_Size() int {
	return xxx_messageInfo_MapMessage.Size(m)
}
func (m *MapMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MapMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MapMessage proto.InternalMessageInfo

func (m *MapMessage) GetMessage() map[string]string {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *MapMessage) GetRequest() map[string]*SearchRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

// extensions and options
type ExtObj struct {
	FooString            string   `protobuf:"bytes,1,opt,name=foo_string,json=fooString,proto3" json:"foo_string,omitempty"`
	BarInt               int64    `protobuf:"varint,2,opt,name=bar_int,json=barInt,proto3" json:"bar_int,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtObj) Reset()         { *m = ExtObj{} }
func (m *ExtObj) String() string { return proto.CompactTextString(m) }
func (*ExtObj) ProtoMessage()    {}
func (*ExtObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{8}
}

func (m *ExtObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtObj.Unmarshal(m, b)
}
func (m *ExtObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtObj.Marshal(b, m, deterministic)
}
func (m *ExtObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtObj.Merge(m, src)
}
func (m *ExtObj) XXX_Size() int {
	return xxx_messageInfo_ExtObj.Size(m)
}
func (m *ExtObj) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtObj.DiscardUnknown(m)
}

var xxx_messageInfo_ExtObj proto.InternalMessageInfo

func (m *ExtObj) GetFooString() string {
	if m != nil {
		return m.FooString
	}
	return ""
}

func (m *ExtObj) GetBarInt() int64 {
	if m != nil {
		return m.BarInt
	}
	return 0
}

type FieldOption struct {
	// 自定义的option
	Foo string `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	// protobuf内置的option
	Bar                  string   `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldOption) Reset()         { *m = FieldOption{} }
func (m *FieldOption) String() string { return proto.CompactTextString(m) }
func (*FieldOption) ProtoMessage()    {}
func (*FieldOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{9}
}

func (m *FieldOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOption.Unmarshal(m, b)
}
func (m *FieldOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOption.Marshal(b, m, deterministic)
}
func (m *FieldOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOption.Merge(m, src)
}
func (m *FieldOption) XXX_Size() int {
	return xxx_messageInfo_FieldOption.Size(m)
}
func (m *FieldOption) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOption.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOption proto.InternalMessageInfo

func (m *FieldOption) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

// Deprecated: Do not use.
func (m *FieldOption) GetBar() string {
	if m != nil {
		return m.Bar
	}
	return ""
}

type MessageOption struct {
	Foo                  string   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageOption) Reset()         { *m = MessageOption{} }
func (m *MessageOption) String() string { return proto.CompactTextString(m) }
func (*MessageOption) ProtoMessage()    {}
func (*MessageOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_009d82c06eb8b59d, []int{10}
}

func (m *MessageOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageOption.Unmarshal(m, b)
}
func (m *MessageOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageOption.Marshal(b, m, deterministic)
}
func (m *MessageOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageOption.Merge(m, src)
}
func (m *MessageOption) XXX_Size() int {
	return xxx_messageInfo_MessageOption.Size(m)
}
func (m *MessageOption) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageOption.DiscardUnknown(m)
}

var xxx_messageInfo_MessageOption proto.InternalMessageInfo

func (m *MessageOption) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

var E_FieldOptString = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1001,
	Name:          "example.everything.field_opt_string",
	Tag:           "bytes,1001,opt,name=field_opt_string",
	Filename:      "a_bit_of_everything.proto",
}

var E_FieldOptObj = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*ExtObj)(nil),
	Field:         1002,
	Name:          "example.everything.field_opt_obj",
	Tag:           "bytes,1002,opt,name=field_opt_obj",
	Filename:      "a_bit_of_everything.proto",
}

var E_MsgOptString = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1001,
	Name:          "example.everything.msg_opt_string",
	Tag:           "bytes,1001,opt,name=msg_opt_string",
	Filename:      "a_bit_of_everything.proto",
}

var E_MsgOptObj = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*ExtObj)(nil),
	Field:         1002,
	Name:          "example.everything.msg_opt_obj",
	Tag:           "bytes,1002,opt,name=msg_opt_obj",
	Filename:      "a_bit_of_everything.proto",
}

var E_FileOptString = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1001,
	Name:          "example.everything.file_opt_string",
	Tag:           "bytes,1001,opt,name=file_opt_string",
	Filename:      "a_bit_of_everything.proto",
}

var E_FileOptObj = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*ExtObj)(nil),
	Field:         1002,
	Name:          "example.everything.file_opt_obj",
	Tag:           "bytes,1002,opt,name=file_opt_obj",
	Filename:      "a_bit_of_everything.proto",
}

var E_SrvOptString = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1001,
	Name:          "example.everything.srv_opt_string",
	Tag:           "bytes,1001,opt,name=srv_opt_string",
	Filename:      "a_bit_of_everything.proto",
}

var E_SrvOptObj = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*ExtObj)(nil),
	Field:         1002,
	Name:          "example.everything.srv_opt_obj",
	Tag:           "bytes,1002,opt,name=srv_opt_obj",
	Filename:      "a_bit_of_everything.proto",
}

var E_MethodOptString = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1001,
	Name:          "example.everything.method_opt_string",
	Tag:           "bytes,1001,opt,name=method_opt_string",
	Filename:      "a_bit_of_everything.proto",
}

var E_MethodOptObj = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*ExtObj)(nil),
	Field:         1002,
	Name:          "example.everything.method_opt_obj",
	Tag:           "bytes,1002,opt,name=method_opt_obj",
	Filename:      "a_bit_of_everything.proto",
}

func init() {
	proto.RegisterEnum("example.everything.Status", Status_name, Status_value)
	proto.RegisterEnum("example.everything.ReservedEnum", ReservedEnum_name, ReservedEnum_value)
	proto.RegisterEnum("example.everything.SearchResponse_Status", SearchResponse_Status_name, SearchResponse_Status_value)
	proto.RegisterType((*SearchRequest)(nil), "example.everything.SearchRequest")
	proto.RegisterType((*ReservedMessage)(nil), "example.everything.ReservedMessage")
	proto.RegisterType((*SearchResponse)(nil), "example.everything.SearchResponse")
	proto.RegisterType((*SearchResponse_Result)(nil), "example.everything.SearchResponse.Result")
	proto.RegisterType((*OtherResponse)(nil), "example.everything.OtherResponse")
	proto.RegisterType((*RepeatedMessage)(nil), "example.everything.RepeatedMessage")
	proto.RegisterType((*AnyMessage)(nil), "example.everything.AnyMessage")
	proto.RegisterType((*OneOfMessage)(nil), "example.everything.OneOfMessage")
	proto.RegisterType((*MapMessage)(nil), "example.everything.MapMessage")
	proto.RegisterMapType((map[string]string)(nil), "example.everything.MapMessage.MessageEntry")
	proto.RegisterMapType((map[string]*SearchRequest)(nil), "example.everything.MapMessage.RequestEntry")
	proto.RegisterType((*ExtObj)(nil), "example.everything.extObj")
	proto.RegisterType((*FieldOption)(nil), "example.everything.FieldOption")
	proto.RegisterType((*MessageOption)(nil), "example.everything.MessageOption")
	proto.RegisterExtension(E_FieldOptString)
	proto.RegisterExtension(E_FieldOptObj)
	proto.RegisterExtension(E_MsgOptString)
	proto.RegisterExtension(E_MsgOptObj)
	proto.RegisterExtension(E_FileOptString)
	proto.RegisterExtension(E_FileOptObj)
	proto.RegisterExtension(E_SrvOptString)
	proto.RegisterExtension(E_SrvOptObj)
	proto.RegisterExtension(E_MethodOptString)
	proto.RegisterExtension(E_MethodOptObj)
}

func init() {
	proto.RegisterFile("a_bit_of_everything.proto", fileDescriptor_009d82c06eb8b59d)
}

var fileDescriptor_009d82c06eb8b59d = []byte{
	// 1058 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0xcb, 0x72, 0xe3, 0x44,
	0x17, 0xc7, 0x23, 0x2b, 0xf1, 0xe5, 0xf8, 0xa6, 0xaf, 0x2b, 0x35, 0x9f, 0x63, 0x18, 0xc6, 0xa3,
	0xa2, 0x28, 0x93, 0x29, 0x3c, 0x8c, 0x59, 0x40, 0x19, 0x48, 0x8d, 0x03, 0x36, 0xb9, 0x30, 0x51,
	0x4a, 0x9e, 0x81, 0x2a, 0x60, 0x10, 0x52, 0xd2, 0x72, 0x14, 0x64, 0xb5, 0xa6, 0xd5, 0x36, 0x63,
	0xde, 0x83, 0x1d, 0xaf, 0xc1, 0x4b, 0x64, 0xc9, 0x5b, 0xc0, 0x9e, 0x35, 0x54, 0x5f, 0xe4, 0x4b,
	0xe2, 0x4a, 0xbc, 0x60, 0x41, 0x36, 0x51, 0x1f, 0xf5, 0xf9, 0xf5, 0x5f, 0xff, 0x73, 0xfa, 0x18,
	0x76, 0x5c, 0xc7, 0x0b, 0x98, 0x43, 0x7c, 0x07, 0x4f, 0x30, 0x9d, 0xb2, 0x8b, 0x20, 0x1a, 0xb6,
	0x62, 0x4a, 0x18, 0x41, 0x08, 0xbf, 0x76, 0x47, 0x71, 0x88, 0x5b, 0xf3, 0x37, 0xf5, 0x9d, 0x21,
	0x21, 0xc3, 0x10, 0x3f, 0x16, 0x3b, 0xbc, 0xb1, 0xff, 0xd8, 0x8d, 0xa6, 0x72, 0x7b, 0xbd, 0x71,
	0xfd, 0xd5, 0x39, 0x4e, 0xce, 0x68, 0x10, 0x33, 0x42, 0xe5, 0x0e, 0x33, 0x82, 0xf2, 0x00, 0xbb,
	0xf4, 0xec, 0xc2, 0xc6, 0xaf, 0xc6, 0x38, 0x61, 0x68, 0x1b, 0xb6, 0x5e, 0x8d, 0x31, 0x9d, 0xd6,
	0xb4, 0x86, 0xd6, 0x2c, 0xd8, 0x72, 0x81, 0x1e, 0x40, 0x31, 0x76, 0x87, 0xd8, 0x89, 0xc6, 0x23,
	0x0f, 0xd3, 0x5a, 0xa6, 0xa1, 0x35, 0xb7, 0x6c, 0xe0, 0xa1, 0x13, 0x11, 0x41, 0xef, 0x40, 0x95,
	0xe2, 0x64, 0x1c, 0x32, 0x27, 0xc6, 0xd4, 0xe1, 0x2f, 0x6a, 0xba, 0xd8, 0x54, 0x96, 0xe1, 0x53,
	0x4c, 0x4f, 0xdd, 0x21, 0x36, 0xdf, 0x83, 0xaa, 0x8d, 0x13, 0x4c, 0x27, 0xf8, 0xfc, 0x19, 0x4e,
	0x12, 0x77, 0x88, 0x8f, 0x36, 0xf3, 0x19, 0x43, 0x3f, 0xda, 0xcc, 0x57, 0x0d, 0xe3, 0x68, 0x33,
	0x5f, 0x30, 0x4a, 0xb6, 0xee, 0x13, 0x62, 0xeb, 0x9e, 0x4b, 0xcd, 0xbf, 0x34, 0xa8, 0xa4, 0xfa,
	0x92, 0x98, 0x44, 0x09, 0x46, 0x5d, 0xc8, 0x4a, 0xa4, 0x50, 0x58, 0x6c, 0xbf, 0xdb, 0xba, 0xe9,
	0x49, 0x6b, 0x39, 0xa7, 0x65, 0x8b, 0x04, 0x5b, 0x25, 0x72, 0x44, 0xc2, 0x5c, 0x36, 0x4e, 0xc4,
	0x87, 0x54, 0xd6, 0x42, 0x0c, 0x44, 0x82, 0xad, 0x12, 0xeb, 0xef, 0x43, 0x56, 0x42, 0x91, 0x01,
	0xfa, 0x98, 0x86, 0xca, 0x2e, 0xfe, 0xc8, 0x2d, 0x64, 0x01, 0x0b, 0xb1, 0xa0, 0x17, 0x6c, 0xb9,
	0x30, 0x1f, 0x41, 0x56, 0x32, 0x50, 0x15, 0x8a, 0x2f, 0x4e, 0x06, 0xa7, 0xbd, 0xcf, 0x0e, 0xfb,
	0x87, 0xbd, 0xcf, 0x8d, 0x0d, 0x94, 0x85, 0x8c, 0x75, 0x6c, 0x68, 0x28, 0x0f, 0x9b, 0xfd, 0xee,
	0xe1, 0x97, 0x46, 0xc6, 0xfc, 0x45, 0x83, 0xb2, 0xc5, 0x2e, 0x30, 0xfd, 0x6f, 0x7d, 0xb6, 0xf9,
	0xab, 0xc6, 0xeb, 0x17, 0x63, 0x97, 0xcd, 0xea, 0x87, 0x3e, 0x85, 0x3c, 0x95, 0xcd, 0x93, 0xd4,
	0xb4, 0x86, 0xde, 0x2c, 0xb6, 0x1f, 0xde, 0x06, 0x16, 0x3b, 0xed, 0x59, 0x0a, 0x6a, 0x2f, 0xa8,
	0xd2, 0x9b, 0x95, 0x76, 0x7d, 0x65, 0xf2, 0x92, 0x0c, 0x74, 0x0f, 0xb2, 0xaa, 0x13, 0xf5, 0x86,
	0xde, 0xdc, 0xb2, 0xd5, 0xca, 0xfc, 0x0a, 0xa0, 0x1b, 0x4d, 0x53, 0x61, 0x35, 0xc8, 0x8d, 0xe4,
	0xa3, 0xaa, 0x4e, 0xba, 0x44, 0x2d, 0xc8, 0x9d, 0x63, 0xe6, 0x06, 0xa1, 0xb4, 0xa2, 0xd8, 0xde,
	0x6e, 0xc9, 0x9b, 0xd2, 0x4a, 0x6f, 0x4a, 0xab, 0x1b, 0x4d, 0xed, 0x74, 0x93, 0xf9, 0x14, 0x4a,
	0x56, 0x84, 0x2d, 0x3f, 0x25, 0x1b, 0x90, 0x19, 0x3d, 0x91, 0xd0, 0x83, 0x0d, 0x3b, 0x33, 0x7a,
	0x22, 0x22, 0x6d, 0x79, 0x2f, 0x44, 0xa4, 0xbd, 0x5f, 0x02, 0x60, 0x38, 0x61, 0x0e, 0x89, 0x30,
	0xf1, 0xcd, 0xdf, 0x32, 0x00, 0xcf, 0xdc, 0x38, 0x05, 0xf4, 0x16, 0xa5, 0x71, 0xcb, 0x1e, 0xad,
	0xfa, 0xea, 0x79, 0x42, 0x4b, 0xfd, 0xef, 0x45, 0x8c, 0x4e, 0xe7, 0xdf, 0xd1, 0x83, 0x9c, 0xf2,
	0x51, 0x98, 0x77, 0x37, 0x46, 0xd9, 0xaf, 0x30, 0x2a, 0xb7, 0xde, 0x81, 0xd2, 0x22, 0x9f, 0xb7,
	0xf4, 0x8f, 0x38, 0x9d, 0x00, 0xfc, 0x91, 0xb7, 0xf4, 0xc4, 0x0d, 0xc7, 0xb3, 0x96, 0x16, 0x8b,
	0x4e, 0xe6, 0x23, 0xad, 0xfe, 0x12, 0x4a, 0x8b, 0xd0, 0x15, 0xb9, 0x1f, 0x2e, 0xe6, 0xae, 0xd5,
	0x1c, 0x73, 0xbc, 0xf9, 0x14, 0xb2, 0xf8, 0x35, 0xb3, 0xbc, 0x4b, 0x74, 0x1f, 0xc0, 0x27, 0xc4,
	0x49, 0x18, 0x0d, 0xa2, 0xa1, 0xe2, 0x17, 0x7c, 0x42, 0x06, 0x22, 0x80, 0xfe, 0x0f, 0x39, 0xcf,
	0xa5, 0x4e, 0x10, 0x31, 0x71, 0x8e, 0x6e, 0x67, 0x3d, 0x97, 0x1e, 0x46, 0xcc, 0xfc, 0x02, 0x8a,
	0xfd, 0x00, 0x87, 0xe7, 0x56, 0xcc, 0x02, 0x12, 0x21, 0x13, 0xf8, 0x74, 0x91, 0xf9, 0xfb, 0xc6,
	0xd5, 0x9e, 0xee, 0x7a, 0x67, 0xbf, 0xef, 0xe5, 0x44, 0xd4, 0xd0, 0xc4, 0xe8, 0x41, 0xdb, 0xc0,
	0x87, 0x8f, 0xfc, 0xd6, 0xfd, 0x4c, 0x4d, 0x93, 0xb3, 0xe8, 0x13, 0x28, 0x2b, 0x97, 0x14, 0xca,
	0x58, 0x40, 0x89, 0xc4, 0xce, 0xce, 0xd5, 0x5e, 0xe9, 0x00, 0x87, 0x21, 0x69, 0xfc, 0x44, 0x68,
	0x78, 0xfe, 0x70, 0x0e, 0xde, 0x7d, 0x39, 0xbb, 0xfe, 0xf7, 0x00, 0x0d, 0x9e, 0x77, 0x9f, 0xbf,
	0x18, 0x38, 0xcb, 0x53, 0xa0, 0x0c, 0x05, 0x15, 0x17, 0xc3, 0xa0, 0x0a, 0x45, 0xb5, 0x94, 0x33,
	0x01, 0xbd, 0x01, 0x95, 0x59, 0xde, 0xf1, 0x89, 0xf5, 0xf5, 0x89, 0xf1, 0x77, 0xfa, 0xa7, 0xed,
	0x7e, 0xcc, 0xcb, 0x20, 0xe7, 0x6a, 0x2f, 0x1a, 0x8f, 0xd0, 0x16, 0x68, 0x7d, 0x63, 0xc3, 0xe4,
	0xb3, 0x35, 0x63, 0xf2, 0xd9, 0x5a, 0x35, 0xf9, 0x6c, 0x2d, 0x9a, 0xf9, 0x7c, 0x53, 0xe4, 0xe5,
	0x76, 0xf5, 0xbe, 0x65, 0xed, 0xea, 0xfb, 0x5d, 0xbb, 0xfd, 0x43, 0xfa, 0x23, 0x30, 0xc0, 0x74,
	0x12, 0x9c, 0x61, 0x64, 0x41, 0x56, 0x06, 0xd0, 0xdd, 0xd5, 0xaa, 0x9b, 0x77, 0x8f, 0x91, 0xf6,
	0xcf, 0xfc, 0x04, 0xc1, 0x56, 0xde, 0xb9, 0xff, 0xf2, 0x09, 0x26, 0x2f, 0xa5, 0x4f, 0xc8, 0xdc,
	0xf1, 0x7a, 0x56, 0x46, 0x3a, 0x07, 0x60, 0xf8, 0xbc, 0x01, 0x1c, 0x12, 0x33, 0xd5, 0x3e, 0xe8,
	0xfe, 0x8d, 0xfb, 0xbe, 0xd0, 0x23, 0x49, 0xed, 0x8f, 0x9c, 0xa8, 0x69, 0xc5, 0x57, 0x41, 0xd9,
	0x63, 0x9d, 0xef, 0xa1, 0x3c, 0x27, 0x11, 0xde, 0x93, 0xb7, 0x63, 0xfe, 0xcc, 0x89, 0x8e, 0x5f,
	0x39, 0xd1, 0x64, 0x57, 0xdb, 0xc5, 0xf4, 0x08, 0xcb, 0xbb, 0xec, 0xf4, 0xa1, 0x32, 0x4a, 0x86,
	0x8b, 0x3a, 0x1f, 0xdc, 0x38, 0x60, 0xa9, 0x05, 0x67, 0x4a, 0x4b, 0xa3, 0x64, 0x38, 0xd7, 0xf9,
	0x1d, 0x14, 0x53, 0x0e, 0x57, 0x79, 0x27, 0x64, 0x0d, 0x9d, 0x05, 0x79, 0x00, 0x57, 0xd9, 0x83,
	0xaa, 0x1f, 0x84, 0x78, 0x51, 0xe6, 0x9b, 0x2b, 0x7c, 0x08, 0xaf, 0x6b, 0x2c, 0xfb, 0x32, 0xa6,
	0x44, 0x7e, 0x0b, 0xa5, 0x19, 0x86, 0xab, 0xbc, 0x9d, 0xb1, 0x86, 0x44, 0x50, 0x7c, 0xe5, 0x64,
	0x42, 0x27, 0xb7, 0x3b, 0xb9, 0xd4, 0x90, 0x73, 0x27, 0x13, 0x3a, 0x59, 0x72, 0x32, 0xe5, 0xac,
	0x76, 0xf2, 0x1a, 0x64, 0x1d, 0x27, 0xe5, 0x01, 0x5c, 0xe5, 0x31, 0xfc, 0x6f, 0x84, 0xd9, 0x05,
	0x59, 0x6a, 0xcd, 0xb7, 0x56, 0x54, 0x8b, 0xef, 0xb9, 0xa6, 0xb3, 0x3a, 0x4a, 0xa3, 0x4a, 0xaa,
	0x0b, 0x95, 0x05, 0x18, 0x57, 0x7b, 0x17, 0x69, 0x0d, 0xb1, 0xa5, 0xd9, 0x29, 0x96, 0x77, 0xb9,
	0xff, 0xf6, 0xd5, 0xde, 0xac, 0x66, 0x9c, 0x30, 0xbf, 0x6c, 0xdf, 0x14, 0x14, 0x23, 0xf6, 0xbc,
	0xac, 0x38, 0xee, 0x83, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xab, 0x3a, 0xca, 0xe6, 0xc7, 0x0a,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/example.everything.SearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

// UnimplementedSearchServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (*UnimplementedSearchServiceServer) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.everything.SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.everything.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a_bit_of_everything.proto",
}

// ServiceOptionClient is the client API for ServiceOption service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceOptionClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type serviceOptionClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceOptionClient(cc grpc.ClientConnInterface) ServiceOptionClient {
	return &serviceOptionClient{cc}
}

func (c *serviceOptionClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/example.everything.ServiceOption/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceOptionServer is the server API for ServiceOption service.
type ServiceOptionServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

// UnimplementedServiceOptionServer can be embedded to have forward compatible implementations.
type UnimplementedServiceOptionServer struct {
}

func (*UnimplementedServiceOptionServer) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterServiceOptionServer(s *grpc.Server, srv ServiceOptionServer) {
	s.RegisterService(&_ServiceOption_serviceDesc, srv)
}

func _ServiceOption_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceOptionServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.everything.ServiceOption/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceOptionServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceOption_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.everything.ServiceOption",
	HandlerType: (*ServiceOptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _ServiceOption_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a_bit_of_everything.proto",
}
